const tags = [
  "Life",
  "Startup",
  "Blockchain",
  "Poetry",
  "Life Lessons",
  "Politics",
  "Health",
  "Love",
  "Travel",
  "Technology",
  "Entrepreneurship",
  "Self Improvement",
  "Education",
  "Writing",
  "Business",
  "Cryptocurrency",
  "Bitcoin",
  "Design",
  "Social Media",
  "Music",
  "Relationships",
  "Coronavirus",
  "Sports",
  "Mental Health",
  "Productivity",
  "Programming",
  "Food",
  "Leadership",
  "Javascript",
  "Art",
  "Fiction",
  "Humor",
  "Artificial Intelligence",
  "UX",
  "Books",
  "Culture",
  "UI",
  "Photography",
  "Creativity",
  "Data Science",
  "Psychology",
  "Software Development",
  "World",
  "Investing",
  "Innovation",
  "Science",
  "Parenting",
  "Gaming",
  "Self",
  "Family",
  "Advice",
  "Architecture",
  "Climate Change",
  "Cooking",
  "Diversity",
  "Economics",
  "Energy",
  "Fashion",
  "Feminism",
  "Finance",
  "Future",
  "Government",
  "History",
  "Ideas",
  "Internet of Things",
  "Journalism",
  "LGBTQ",
  "Movies",
  "NBA",
  "Privacy",
  "Racism",
  "Reading",
  "Satire",
  "Self Driving Cars",
  "Short Story",
  "Space",
  "Sustainability",
  "Television",
  "This Happened To Me",
  "Transportation",
  "Venture Capital",
  "Virtual Reality",
  "Women In Tech",
];

export default tags;
